### ISSUE TITLE
collaborate with virtual-dom

### ISSUE THREAD

**Issue by Raynos** [Swatinem/virtualdom#1]
Hi @Swatinem 

Myself & @Matt-Esch work on virtual-dom

> virtual-dom seems like a very good solution. It is made for use with browserify and pulls in the complete semver package as a dependency facepalm.

We have since refactored `virtual-dom` to not depend on `semver`.

We also intend to refactor `virtual-dom` further into a virtual tree, a virtual dom and a h dsl.

It would be cool to collaborate / share ideas.

**Comment by Swatinem** [comment]
> We have since refactored virtual-dom to not depend on semver.

It’s still used in vtree/version though. :-)

So I’m using my implementation with `component` so would have to make your work with that as well, if its no problem.

Otherwise I haven’t taken that deep a look at your implementation, but mine takes advantage things like ClassList and does more fine-grained diffing for classes and inline styles. Not sure those are widely used in the real world though.

I will just open a few tickets over at your repo for things that I would need.

**Comment by Matt-Esch** [comment]
Everything makes trade offs. All of these implementations can be learnt from. Semver is now out of virtual-dom completely. It's interesting to see what you are optimizing for and how virtual-dom can be made more appropriate for your use case. ClassList optimization does seem like a very minor win (if it even is one) over some of the major optimizations we could be worrying about. I think, for example, going down the immutable vdom tree route is actually really powerful. It opens up caching options that mutable trees wouldn't be good enough for.

Thanks for the issues though, I really appreciate the feedback.

**Comment by Swatinem** [comment]
Yes, making things immutable indeed opens up quite some possibilities. But it is also really hard to do, depending on what kind of models you want to use.

**Comment by gnimmelf** [comment]
Keep going guys! =)
